Update test.yaml
Deleteing coveralls due to this issue when trying to rerun tests:
Run coverallsapp/github-action@1.1.3
Using lcov file: ./coverage/lcov.info
Error: Bad response: 422 {"message":"Can't add a job to a build that is already closed. Build 6418524116 is closed. See docs.coveralls.io/parallel-builds","error":true}